# Generated by Django 5.1.1 on 2024-09-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(verbose_name="Начало выполнения привычки"),
        ),
    ]
